### ISSUE TITLE
danger: dangerfile.ts does not type-check (pr.labels missing from GitHubPRDSL)

### ISSUE THREAD

**Issue by LucasSantana-Dev** [LucasSantana-Dev/Lucky#2203]
Found while type-checking the lockfile-guard change in #2202. `dangerfile.ts` is not covered by any workspace `type:check`, and a standalone check fails:

```
npx tsc --noEmit --ignoreConfig --esModuleInterop --skipLibCheck --target es2022 --module esnext --moduleResolution bundler dangerfile.ts
dangerfile.ts(72,8): error TS2339: Property 'labels' does not exist on type 'GitHubPRDSL'.
```

`dangerfile.ts:70-73` reads `pr.labels?.some(...)` for the `skip-changelog` label. Danger 13's `GitHubPRDSL` type has no `labels` field, so the skip-label check only works because Danger transpiles without type-checking. At runtime the REST payload does carry `labels`, so behaviour is fine; the type lies. Pre-existing on `main` (reproduces at c078aca9), not introduced by #2202.

Fix shape: read labels from `danger.github.issue.labels` (typed) instead of `pr.labels`, and add `dangerfile.ts` to a type-check step (root `tsc` invocation or a tiny `tsconfig.danger.json`) so the file stays checked.
